name: "Infrastructure as Code Deployment"

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - dev
    # paths:
    #   - 'deploy/**'

  pull_request:
    branches:
      - main
      - dev
    # paths:
    #   - 'deploy/**'      

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: dev

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true
      ARM_USE_AZUREAD: true
      TF_BACKEND_STORAGE_ACCOUNT_NAME: ${{ vars.TF_BACKEND_STORAGE_ACCOUNT_NAME }}
      TF_BACKEND_CONTAINER_NAME: ${{ vars.TF_BACKEND_CONTAINER_NAME }}
      TF_ENV: dev

    steps:
      - uses: actions/checkout@v4

      - name: "Azure Login"
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}

      - name: Generate backend.tf
        run: |
          cat > ./deploy/backend.tf <<EOF
          terraform {
            backend "azurerm" {  
              storage_account_name  = "${{ env.TF_BACKEND_STORAGE_ACCOUNT_NAME }}"
              container_name        = "${{ env.TF_BACKEND_CONTAINER_NAME }}"
              key                   = "${{ env.TF_ENV }}.api.tfstate" 
            }
          }
          EOF          

      # - name: "Set Terraform environment variables"
      #   run: |
      #     echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
      #     echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
      #     echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV

      # - name: "Setup Terraform"
      #   uses: hashicorp/setup-terraform@v3
      #   with:
      #     terraform_version: "1.5.0" # Or a version you prefer

      # - name: "Terraform Init"
      #   id: init
      #   run: terraform init
      #   working-directory: deploy/

      # - name: "Terraform Plan"
      #   id: plan
      #   run: terraform plan -var-file="environments/dev.tfvars"
      #   working-directory: deploy/

  # terraform-apply:
  #   needs: terraform-plan
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #   environment: dev
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: "Azure Login"
  #       uses: azure/login@v1
  #       with:
  #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}

  #     - name: "Set Terraform environment variables"
  #       run: |
  #         echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
  #         echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
  #         echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV

  #     - name: "Setup Terraform"
  #       uses: hashicorp/setup-terraform@v3
  #       with:
  #         terraform_version: "1.5.0"

  #     - name: "Terraform Init"
  #       run: terraform init
  #       working-directory: deploy/

  #     - name: "Terraform Apply"
  #       run: terraform apply -auto-approve -var-file="environments/dev.tfvars"
  #       working-directory: deploy/